CREATE TABLE ERS_SCHEDULE_DELIVERY
(
   DELIVERY_NAME varchar2(50),
   GROUP_NAME varchar2(50),
   SETTING varchar2(1000)
);

CREATE TABLE ERS_SCHEDULE_TASK
(
   TASK_NAME varchar2(50) PRIMARY KEY NOT NULL,
   GROUP_NAME varchar2(50),
   REQUEST varchar2(1024)
);

CREATE TABLE ERS_SCHEDULE_TASKGROUP
(   GROUP_NAME varchar2(50) PRIMARY KEY NOT NULL,
   SCHEDULE varchar2(1000),
   STARTTIME date,
   ENDTYPE varchar(100),
   ENDOPTION varchar(100),
   DESCRIPTION varchar2(1024),
   ENABLE decimal(1)
);

CREATE TABLE ERS_SCHEDULE_TASKHISTORY
(
   GROUP_NAME varchar2(50) NOT NULL,
   LASTUPDATEDATE date NOT NULL,
   STATUS decimal(2),
   DESCRIPTION varchar2(1024)
);
