CREATE TABLE ERS_SCHEDULE_DELIVERY
(
   DELIVERY_NAME varchar(50),
   GROUP_NAME varchar(50),
   SETTING memo
);

CREATE TABLE ERS_SCHEDULE_TASK
(
   TASK_NAME varchar(50) PRIMARY KEY NOT NULL,
   GROUP_NAME varchar(50),
   REQUEST memo
);

CREATE TABLE ERS_SCHEDULE_TASKGROUP
(   GROUP_NAME varchar(50) PRIMARY KEY NOT NULL,
   SCHEDULE memo,
   STARTTIME timestamp ,
   ENDTYPE varchar(100),
   ENDOPTION varchar(100),
   DESCRIPTION memo,
   ENABLE number
);

CREATE TABLE ERS_SCHEDULE_TASKHISTORY
(
   GROUP_NAME varchar(50) NOT NULL,
   LASTUPDATEDATE timestamp  NOT NULL,
   STATUS memo,
   DESCRIPTION memo
);

